/***************************************************************
    *  DO NOT EDIT THIS FILE!
    *         
    *  This file is automatically generated by HP Service Test.
    *  Manually changing the contents of this file may result in 
    *  loss of information.
    *          
    *  To edit the test, open the file ‘FlightAPI_REST.st’ 
    *  in HP Service Test.
     ***************************************************************/
    
    namespace Script
    {
    using System;
    using System.Text;
    using System.Threading;
    using System.Xml;
    using System.Xml.Schema;
    using HP.ST.Fwk.ReporterFWK;
    using HP.ST.Shared.Utilities;
    using HP.ST.Ext.BindingImpl.Getters;
    using HP.ST.Ext.BindingImpl.Setters;
    using HP.ST.Fwk.RunTimeFWK.BindingFWK;
    using HP.ST.Fwk.RunTimeFWK.BindingFWK.PropInfo;
    using HP.ST.Fwk.RunTimeFWK.BindingFWK.Getters;
    using HP.ST.Fwk.RunTimeFWK.BindingFWK.Setters;
    using HP.ST.Fwk.RunTimeFWK;
    using HP.ST.Fwk.RunTimeFWK.Utilities;
    using HP.ST.Fwk.RunTimeFWK.HelperClasses;
    using HP.ST.Fwk.RunTimeFWK.CompositeActivities;
    using HP.ST.Ext.BindingImpl.Setters.DataSourceSetters;
    using HP.ST.Fwk.JVMLoader;
    using System.IO;
    using System.Collections.Generic;
    using System.Reflection;
    using HP.ST.Fwk.SOAReplayAPI;
    using HP.ST.Fwk.UFTLicensing;
    
    
    
    public partial class WorkFlowScript : STWorkFlowScriptBase
    {    
    	TestUserCode _userCode = null;
    	TestEntities _flow = null;
    	static Reporter reporter;
    	int reportLevelInTree;
        HP.ST.Fwk.ReportCreator.QTPEngine.QTPEngineReportCreator reportCreator;
    	
    	public BindDirection bind_dir5 = null;
        public BindDirection bind_dir6 = null;
        public BindDirection bind_dir7 = null;
        public BindDirection bind_dir8 = null;
        public BindDirection bind_dir9 = null;
        public BindDirection bind_dir10 = null;
        public BindDirection bind_dir11 = null;
        public BindDirection bind_dir12 = null;
        
        public IEnumerable<FeaturesGroup> LicensedFeatures
        {
        
        get
        {
        List<FeaturesGroup> features = new List<FeaturesGroup>();
        return features;
        
        }
        
        }
        
        public WorkFlowScript()
            : base(VuserClass.CommandLineArguments, new STRunTimeContext(), "test")
        {	
        	UpdateContextWithActionFolder(String.Empty);
        	
        }
        
        public WorkFlowScript(ISTRunTimeContext ctx)
            : base(VuserClass.CommandLineArguments, ctx, "test")
            
        {
        	this._context = ctx;
        	UpdateContextWithActionFolder(String.Empty);
        	UpdateTestSettings(ctx);
        }
        
        internal void InitializeComponent()
        {
        	LoadInput();
        	
        	InitReport();
        	
        	InitializeEncryptionManagerValues();
        
        	_userCode = new TestUserCode();
            _flow = _userCode;
            _flow.Context=this._context;
            
            
        
        	_flow.DataFetchActivity10 = new HP.ST.Ext.BasicActivities.DataFetchActivity(_context,"DataFetchActivity10");
            _flow.DataFetchActivity7 = new HP.ST.Ext.BasicActivities.DataFetchActivity(_context,"DataFetchActivity7");
            _flow.StartActivity1 = new HP.ST.Ext.BasicActivities.StartActivity(_context,"StartActivity1");
            _flow.Loop2 = new HP.ST.Fwk.RunTimeFWK.CompositeActivities.Loop<Loop2Input>(_context,"Loop2",LoopType.For);
            _flow.DataExporterActivity9 = new HP.ST.Ext.BasicActivities.DataExporterActivity(_context,"DataExporterActivity9");
            _flow.DataExporterActivity12 = new HP.ST.Ext.BasicActivities.DataExporterActivity(_context,"DataExporterActivity12");
            _flow.DataExporterCloseActivity13 = new HP.ST.Ext.BasicActivities.DataExporterCloseActivity(_context,"DataExporterCloseActivity13");
            _flow.EndActivity3 = new HP.ST.Ext.BasicActivities.EndActivity(_context,"EndActivity3");
            _flow.DataDisconnectActivity8 = new HP.ST.Ext.BasicActivities.DataDisconnectActivity(_context,"DataDisconnectActivity8");
            _flow.DataDisconnectActivity11 = new HP.ST.Ext.BasicActivities.DataDisconnectActivity(_context,"DataDisconnectActivity11");
            _flow.Sequence6 = new HP.ST.Fwk.RunTimeFWK.CompositeActivities.Sequence(_context,"Sequence6");
            _flow.RESTActivityV24 = new HP.ST.Ext.RestActivity.RESTActivityV2<RESTActivityV24Input,RESTActivityV24Output>(_context,"RESTActivityV24");
            _flow.RESTActivityV25 = new HP.ST.Ext.RestActivity.RESTActivityV2<RESTActivityV25Input,RESTActivityV25Output>(_context,"RESTActivityV25");
            _flow.DataFetchActivity10.Comment = @"";
            _flow.DataFetchActivity10.IconPath = @"";
            _flow.DataFetchActivity10.AssemblyPath = @"AddIns\ServiceTest\BaseDataProviders\HP.ST.Ext.CustomDataProviders.dll";
            _flow.DataFetchActivity10.QueryClassName = @"HP.ST.Ext.CustomDataProviders.ExcelFileDataQuery";
            XmlDocument DataFetchActivity10_QueryParameters_Document = new XmlDocument();
            DataFetchActivity10_QueryParameters_Document.PreserveWhitespace = true;
            string xmlDataFetchActivity10Params = @"<Arguments><QueryParametersContainer><QueryParameter><Name>Id</Name><Value>448598d8-7b2d-448b-b468-bbb801d6a5b6</Value></QueryParameter><QueryParameter><Name>QueryName</Name><Value>FlightAPIDataSource!Output</Value></QueryParameter><QueryParameter><Name>IsEmbedded</Name><Value>True</Value></QueryParameter><QueryParameter><Name>Externalized</Name><Value>True</Value></QueryParameter><QueryParameter><Name>GroupText</Name><Value>FlightAPIDataSource</Value></QueryParameter><QueryParameter><Name>FilePath</Name><Value>" + _context.ResourceManager.GetValue("{FlightAPIDataSource!Output.TablePath}") + "</Value></QueryParameter><QueryParameter><Name>SheetName</Name><Value>Output$</Value></QueryParameter><QueryParameter><Name>ContainsHeadersRow</Name><Value>True</Value></QueryParameter></QueryParametersContainer></Arguments>";
            DataFetchActivity10_QueryParameters_Document.LoadXml(xmlDataFetchActivity10Params);
            _flow.DataFetchActivity10.QueryParameters = DataFetchActivity10_QueryParameters_Document;
            _flow.dataSourceNameToDataSource.Add("FlightAPIDataSource!Output", _flow.DataFetchActivity10);
            this.Activities.Add (_flow.DataFetchActivity10);
            _flow.DataFetchActivity7.Comment = @"";
            _flow.DataFetchActivity7.IconPath = @"";
            _flow.DataFetchActivity7.AssemblyPath = @"AddIns\ServiceTest\BaseDataProviders\HP.ST.Ext.CustomDataProviders.dll";
            _flow.DataFetchActivity7.QueryClassName = @"HP.ST.Ext.CustomDataProviders.ExcelFileDataQuery";
            XmlDocument DataFetchActivity7_QueryParameters_Document = new XmlDocument();
            DataFetchActivity7_QueryParameters_Document.PreserveWhitespace = true;
            string xmlDataFetchActivity7Params = @"<Arguments><QueryParametersContainer><QueryParameter><Name>Id</Name><Value>9ca19b4b-997d-46e5-838c-274b5ca58521</Value></QueryParameter><QueryParameter><Name>QueryName</Name><Value>FlightAPIDataSource!Input</Value></QueryParameter><QueryParameter><Name>IsEmbedded</Name><Value>True</Value></QueryParameter><QueryParameter><Name>Externalized</Name><Value>True</Value></QueryParameter><QueryParameter><Name>GroupText</Name><Value>FlightAPIDataSource</Value></QueryParameter><QueryParameter><Name>FilePath</Name><Value>" + _context.ResourceManager.GetValue("{FlightAPIDataSource!Input.TablePath}") + "</Value></QueryParameter><QueryParameter><Name>SheetName</Name><Value>Input$</Value></QueryParameter><QueryParameter><Name>ContainsHeadersRow</Name><Value>True</Value></QueryParameter></QueryParametersContainer></Arguments>";
            DataFetchActivity7_QueryParameters_Document.LoadXml(xmlDataFetchActivity7Params);
            _flow.DataFetchActivity7.QueryParameters = DataFetchActivity7_QueryParameters_Document;
            _flow.dataSourceNameToDataSource.Add("FlightAPIDataSource!Input", _flow.DataFetchActivity7);
            this.Activities.Add (_flow.DataFetchActivity7);
            _flow.StartActivity1.Comment = @"";
            _flow.StartActivity1.IconPath = @"AddIns\ServiceTest\BasicActivities\toolbox_code_activity.png";
            _flow.StartActivity1.Name = @"Start";
            _flow.StartActivity1.JVM = new HP.ST.Ext.BasicActivities.JVMProperties();
            _flow.StartActivity1.IsJavaUsed = false;
            _flow.StartActivity1.JVM.Classpath = @"%CLASSPATH%";
            _flow.StartActivity1.JVM.AdditionalVMParameters = @"";
            _flow.StartActivity1.JMS = new HP.ST.Ext.BasicActivities.JMSProperties();
            _flow.StartActivity1.IsJmsUsed = false;
            _flow.StartActivity1.JMS.JNDIContextFactory = @"<Select...>";
            _flow.StartActivity1.JMS.JNDIProviderUrl = @"";
            _flow.StartActivity1.JMS.JMSConnectionFactory = @"";
            _flow.StartActivity1.JMS.SecurityPrincipal = @"";
            _flow.StartActivity1.JMS.SecurityCredentials = @"";
            _flow.StartActivity1.JMS.JMSClientID = @"";
            _flow.StartActivity1.JMS.SSLPassword = @"";
            _flow.StartActivity1.JMS.SSLTrustedCertificate = @"";
            _flow.StartActivity1.JMS.SSLIdentity = @"";
            _flow.StartActivity1.JMS.ConnectionsPerProcess = @"1";
            _flow.StartActivity1.JMS.TimeoutOptions = @"DN_User_defined_Timeout";
            _flow.StartActivity1.JMS.UserTimeout = @"20";
            _flow.StartActivity1.JMS.GenerateAutoSelector = @"No";
            this.Activities.Add (_flow.StartActivity1);
            _flow.Loop2.ConditionAsString = @"Run for 3 iterations";
            _flow.Loop2.NumberOfIterations = (int)3;
            _flow.Loop2.Comment = @"";
            _flow.Loop2.IconPath = @"AddIns\ServiceTest\BasicActivities\toolbox_loop.png";
            _flow.Loop2.Name = @"Test Flow";
            _flow.Loop2.Activities.Add (_flow.Sequence6);
            this.Activities.Add (_flow.Loop2);
            _flow.DataExporterActivity9.Comment = @"";
            _flow.DataExporterActivity9.IconPath = @"";
            VTDPropertyInfoBase pi9 = new VTDPropertyInfoBase("OutTable");
            VTDBaseGetter binding_getter5 = new VTDObjectGetter(pi9);
            VTDPropertyInfoBase pi10 = new VTDPropertyInfoBase("Data");
            VTDBaseSetter binding_setter5 = new VTDObjectSetter(pi10);
            binding_setter5 = new StringFormaterDecorator(binding_setter5,"{Step.DataFetchActivity7.OutTable}");
            bind_dir5 = new BindDirection(_flow.DataFetchActivity7,binding_getter5,binding_setter5,BindTargetType.ToInProperty);
            _flow.DataExporterActivity9.InDirections.Add(bind_dir5);
            this.Activities.Add (_flow.DataExporterActivity9);
            _flow.DataExporterActivity12.Comment = @"";
            _flow.DataExporterActivity12.IconPath = @"";
            VTDPropertyInfoBase pi11 = new VTDPropertyInfoBase("OutTable");
            VTDBaseGetter binding_getter6 = new VTDObjectGetter(pi11);
            VTDPropertyInfoBase pi12 = new VTDPropertyInfoBase("Data");
            VTDBaseSetter binding_setter6 = new VTDObjectSetter(pi12);
            binding_setter6 = new StringFormaterDecorator(binding_setter6,"{Step.DataFetchActivity10.OutTable}");
            bind_dir6 = new BindDirection(_flow.DataFetchActivity10,binding_getter6,binding_setter6,BindTargetType.ToInProperty);
            _flow.DataExporterActivity12.InDirections.Add(bind_dir6);
            this.Activities.Add (_flow.DataExporterActivity12);
            _flow.DataExporterCloseActivity13.Comment = @"";
            _flow.DataExporterCloseActivity13.IconPath = @"";
            this.Activities.Add (_flow.DataExporterCloseActivity13);
            _flow.EndActivity3.Comment = @"";
            _flow.EndActivity3.IconPath = @"AddIns\ServiceTest\BasicActivities\toolbox_code_activity.png";
            _flow.EndActivity3.Name = @"End";
            this.Activities.Add (_flow.EndActivity3);
            _flow.DataDisconnectActivity8.Comment = @"";
            _flow.DataDisconnectActivity8.IconPath = @"";
            VTDPropertyInfoBase pi13 = new VTDPropertyInfoBase("OutTable");
            VTDBaseGetter binding_getter7 = new VTDObjectGetter(pi13);
            VTDPropertyInfoBase pi14 = new VTDPropertyInfoBase("Data");
            VTDBaseSetter binding_setter7 = new VTDObjectSetter(pi14);
            binding_setter7 = new StringFormaterDecorator(binding_setter7,"{Step.DataFetchActivity7.OutTable}");
            bind_dir7 = new BindDirection(_flow.DataFetchActivity7,binding_getter7,binding_setter7,BindTargetType.ToInProperty);
            _flow.DataDisconnectActivity8.InDirections.Add(bind_dir7);
            this.Activities.Add (_flow.DataDisconnectActivity8);
            _flow.DataDisconnectActivity11.Comment = @"";
            _flow.DataDisconnectActivity11.IconPath = @"";
            VTDPropertyInfoBase pi15 = new VTDPropertyInfoBase("OutTable");
            VTDBaseGetter binding_getter8 = new VTDObjectGetter(pi15);
            VTDPropertyInfoBase pi16 = new VTDPropertyInfoBase("Data");
            VTDBaseSetter binding_setter8 = new VTDObjectSetter(pi16);
            binding_setter8 = new StringFormaterDecorator(binding_setter8,"{Step.DataFetchActivity10.OutTable}");
            bind_dir8 = new BindDirection(_flow.DataFetchActivity10,binding_getter8,binding_setter8,BindTargetType.ToInProperty);
            _flow.DataDisconnectActivity11.InDirections.Add(bind_dir8);
            this.Activities.Add (_flow.DataDisconnectActivity11);
            _flow.Sequence6.Comment = @"";
            _flow.Sequence6.IconPath = @"";
            _flow.Sequence6.Name = @"Sequence6";
            _flow.Sequence6.Activities.Add (_flow.RESTActivityV24);
            _flow.Sequence6.Activities.Add (_flow.RESTActivityV25);
            _flow.RESTActivityV24.TextBody = @"";
            _flow.RESTActivityV24.TextXmlBody = @"";
            _flow.RESTActivityV24.FileBody = @"";
            _flow.RESTActivityV24.PostBody = @"";
            _flow.RESTActivityV24.Url = @"http://localhost:8000/Flights_REST/Flights?DepartureCity={Step.RESTInputProperties.RESTActivityV24.DepartureCity}&ArrivalCity={Step.RESTInputProperties.RESTActivityV24.ArrivalCity}&Date={Step.RESTInputProperties.RESTActivityV24.Date}";
            _flow.RESTActivityV24.HttpMethod = @"GET";
            _flow.RESTActivityV24.HttpVersion = @"1.1";
            _flow.RESTActivityV24.RequestHeaders = new Pair<string, string>[2];
            _flow.RESTActivityV24.RequestHeaders[0] = new Pair<string, string>();
            _flow.RESTActivityV24.RequestHeaders[0].Key = @"Accept";
            _flow.RESTActivityV24.RequestHeaders[0].Value = @"application/xml";
            _flow.RESTActivityV24.RequestHeaders[1] = new Pair<string, string>();
            _flow.RESTActivityV24.RequestHeaders[1].Key = @"Content-Type";
            _flow.RESTActivityV24.RequestHeaders[1].Value = @"text/xml";
            _flow.RESTActivityV24.Input.DepartureCity = @"";
            _flow.RESTActivityV24.Input.ArrivalCity = @"";
            _flow.RESTActivityV24.Input.Date =  new DateTime(1,1,1,0,0,0,0);
            _flow.RESTActivityV24.Comment = @"";
            _flow.RESTActivityV24.IconPath = @"AddIns\ServiceTest\REST\ictb_REST_Method_16.png";
            _flow.RESTActivityV24.RequestBodyType = @"Xml";
            _flow.RESTActivityV24.ResponseType = @"Xml";
            _flow.RESTActivityV24.Name = @"GetFlights4";
            _flow.RESTActivityV24.Proxy.Server = @"";
            _flow.RESTActivityV24.Proxy.Username = @"";
            _flow.RESTActivityV24.Proxy.Password = @"";
            _flow.RESTActivityV24.Authentication.Username = @"";
            _flow.RESTActivityV24.Authentication.Password = @"";
            _flow.RESTActivityV24.Authentication.PreemptiveAuthentication = false;
            _flow.RESTActivityV24.ConnectionType = @"Keep-Alive";
            _flow.RESTActivityV24.Timeout = (int)99999;
            _flow.RESTActivityV24.ClientCertificate.Password = @"";
            _flow.RESTActivityV24.ClientCertificate.FileSystem.Path = @"";
            _flow.RESTActivityV24.UseClientCertificate = false;
            _flow.RESTActivityV24.MaximumAutomaticRedirections = (int)3;
            _flow.RESTActivityV24.AllowRedirections = true;
            _flow.RESTActivityV24.ReuseCookies = false;
            _flow.RESTActivityV24.ExpectServerError = false;
            _flow.RESTActivityV24.HanaRequest = false;
            XmlDocument RESTActivityV24_XMLBody_Document = new XmlDocument();
            RESTActivityV24_XMLBody_Document.PreserveWhitespace = true;
            RESTActivityV24_XMLBody_Document.LoadXml("<F6DA54ED-92F5-4c5c-9795-170905F25080 />");
            _flow.RESTActivityV24.XMLBody = RESTActivityV24_XMLBody_Document;
            XmlDocument RESTActivityV24_RequestMultipartInfoXml_Document = new XmlDocument();
            RESTActivityV24_RequestMultipartInfoXml_Document.PreserveWhitespace = true;
            RESTActivityV24_RequestMultipartInfoXml_Document.LoadXml(
@"<RequestMultipartInfo><Type>Related</Type></RequestMultipartInfo>");
            _flow.RESTActivityV24.RequestMultipartInfoXml = RESTActivityV24_RequestMultipartInfoXml_Document;
            _flow.RESTActivityV24.Multipart=false;
            _flow.RESTActivityV24.Input.DepartureCity = @"";
            _flow.RESTActivityV24.Input.ArrivalCity = @"";
            _flow.RESTActivityV24.Input.Date =  new DateTime(1,1,1,0,0,0,0);
            _flow.RESTActivityV24.Input.DepartureCity = @"";
            _flow.RESTActivityV24.Input.ArrivalCity = @"";
            _flow.RESTActivityV24.Input.Date =  new DateTime(1,1,1,0,0,0,0);
            VTDPropertyInfoBase pi17 = new VTDPropertyInfoBase("Input.DepartureCity");
            VTDBaseGetter binding_getter9 = new VTDObjectGetter(pi17);
            VTDPropertyInfoBase pi18 = new VTDPropertyInfoBase("Url");
            VTDBaseSetter binding_setter9 = new VTDObjectSetter(pi18);
            binding_setter9 = new StringFormaterDecorator(binding_setter9,"{Step.RESTInputProperties.RESTActivityV24.DepartureCity}");
            bind_dir9 = new BindDirection(_flow.RESTActivityV24,binding_getter9,binding_setter9,BindTargetType.ToInProperty);
            _flow.RESTActivityV24.InDirections.Add(bind_dir9);
            VTDPropertyInfoBase pi19 = new VTDPropertyInfoBase("Input.ArrivalCity");
            VTDBaseGetter binding_getter10 = new VTDObjectGetter(pi19);
            VTDPropertyInfoBase pi20 = new VTDPropertyInfoBase("Url");
            VTDBaseSetter binding_setter10 = new VTDObjectSetter(pi20);
            binding_setter10 = new StringFormaterDecorator(binding_setter10,"{Step.RESTInputProperties.RESTActivityV24.ArrivalCity}");
            bind_dir10 = new BindDirection(_flow.RESTActivityV24,binding_getter10,binding_setter10,BindTargetType.ToInProperty);
            _flow.RESTActivityV24.InDirections.Add(bind_dir10);
            VTDPropertyInfoBase pi21 = new VTDPropertyInfoBase("Input.Date");
            VTDBaseGetter binding_getter11 = new VTDObjectGetter(pi21);
            VTDPropertyInfoBase pi22 = new VTDPropertyInfoBase("Url");
            VTDBaseSetter binding_setter11 = new VTDObjectSetter(pi22);
            binding_setter11 = new StringFormaterDecorator(binding_setter11,"{Step.RESTInputProperties.RESTActivityV24.Date}");
            bind_dir11 = new BindDirection(_flow.RESTActivityV24,binding_getter11,binding_setter11,BindTargetType.ToInProperty);
            _flow.RESTActivityV24.InDirections.Add(bind_dir11);
            XmlDocument RESTActivityV24_ExpectedResponseXmlBody_Document = new XmlDocument();
            RESTActivityV24_ExpectedResponseXmlBody_Document.PreserveWhitespace = true;
            RESTActivityV24_ExpectedResponseXmlBody_Document.LoadXml(
@"<ArrayOfFlight xmlns=""HP.SOAQ.SampleApp"" xmlns:i=""http://www.w3.org/2001/XMLSchema-instance"">
 <Flight>
   <Airlines>AA</Airlines>
   <ArrivalCity>Denver</ArrivalCity> 
   <ArrivalTime>01:23 PM</ArrivalTime> 
   <DepartureCity>London</DepartureCity> 
   <DepartureTime>06:12 AM</DepartureTime> 
   <FlightNumber>20279</FlightNumber> 
   <Price>112.2</Price>
 </Flight>
</ArrayOfFlight>");
            _flow.RESTActivityV24.ExpectedResponseXmlBody = RESTActivityV24_ExpectedResponseXmlBody_Document;
            XmlDocument RESTActivityV24_ExpectedResponseJsonBody_Document = new XmlDocument();
            RESTActivityV24_ExpectedResponseJsonBody_Document.PreserveWhitespace = true;
            RESTActivityV24_ExpectedResponseJsonBody_Document.LoadXml(
@"<F6DA54ED-92F5-4c5c-9795-170905F25080 />");
            _flow.RESTActivityV24.ExpectedResponseJsonBody = RESTActivityV24_ExpectedResponseJsonBody_Document;
            XmlDocument RESTActivityV24_ExpectedOutputProperties_Document = new XmlDocument();
            RESTActivityV24_ExpectedOutputProperties_Document.PreserveWhitespace = true;
            RESTActivityV24_ExpectedOutputProperties_Document.LoadXml(
@"<Arguments><ResponseHttpVersion></ResponseHttpVersion><StatusCode></StatusCode><StatusDescription></StatusDescription><ResponseBody></ResponseBody><ResponseBodyAsBase64></ResponseBodyAsBase64></Arguments>");
            _flow.RESTActivityV24.ExpectedOutputProperties = RESTActivityV24_ExpectedOutputProperties_Document;
            _flow.RESTActivityV25.TextBody = @"";
            _flow.RESTActivityV25.TextXmlBody = @"";
            _flow.RESTActivityV25.FileBody = @"";
            _flow.RESTActivityV25.PostBody = @"";
            _flow.RESTActivityV25.Url = @"http://localhost:8000/Flights_REST/FlightOrders";
            _flow.RESTActivityV25.HttpMethod = @"POST";
            _flow.RESTActivityV25.HttpVersion = @"1.1";
            _flow.RESTActivityV25.RequestHeaders = new Pair<string, string>[1];
            _flow.RESTActivityV25.RequestHeaders[0] = new Pair<string, string>();
            _flow.RESTActivityV25.RequestHeaders[0].Key = @"Content-Type";
            _flow.RESTActivityV25.RequestHeaders[0].Value = @"text/xml";
            _flow.RESTActivityV25.Comment = @"";
            _flow.RESTActivityV25.IconPath = @"AddIns\ServiceTest\REST\ictb_REST_Method_16.png";
            _flow.RESTActivityV25.RequestBodyType = @"Xml";
            _flow.RESTActivityV25.ResponseType = @"Xml";
            _flow.RESTActivityV25.Name = @"ReserveOrder5";
            _flow.RESTActivityV25.Proxy.Server = @"";
            _flow.RESTActivityV25.Proxy.Username = @"";
            _flow.RESTActivityV25.Proxy.Password = @"";
            _flow.RESTActivityV25.Authentication.Username = @"";
            _flow.RESTActivityV25.Authentication.Password = @"";
            _flow.RESTActivityV25.Authentication.PreemptiveAuthentication = false;
            _flow.RESTActivityV25.ConnectionType = @"Keep-Alive";
            _flow.RESTActivityV25.Timeout = (int)100000;
            _flow.RESTActivityV25.ClientCertificate.Password = @"";
            _flow.RESTActivityV25.ClientCertificate.FileSystem.Path = @"";
            _flow.RESTActivityV25.UseClientCertificate = false;
            _flow.RESTActivityV25.MaximumAutomaticRedirections = (int)3;
            _flow.RESTActivityV25.AllowRedirections = true;
            _flow.RESTActivityV25.ReuseCookies = false;
            _flow.RESTActivityV25.ExpectServerError = false;
            _flow.RESTActivityV25.HanaRequest = false;
            XmlDocument RESTActivityV25_XMLBody_Document = new XmlDocument();
            RESTActivityV25_XMLBody_Document.PreserveWhitespace = true;
            RESTActivityV25_XMLBody_Document.LoadXml(
@"<?xml version=""1.0"" encoding=""utf-8""?>
<FlightOrderDetails xmlns=""HP.SOAQ.SampleApp"">
 <Class></Class>
 <CustomerName></CustomerName>
 <DepartureDate></DepartureDate>
 <FlightNumber>{Step.ResponseXmlBody.RESTActivityV24.Flight.FlightNumber}</FlightNumber>
 <NumberOfTickets></NumberOfTickets>
</FlightOrderDetails>");
            _flow.RESTActivityV25.XMLBody = RESTActivityV25_XMLBody_Document;
            XmlDocument RESTActivityV25_RequestMultipartInfoXml_Document = new XmlDocument();
            RESTActivityV25_RequestMultipartInfoXml_Document.PreserveWhitespace = true;
            RESTActivityV25_RequestMultipartInfoXml_Document.LoadXml(
@"<RequestMultipartInfo><Type>Related</Type></RequestMultipartInfo>");
            _flow.RESTActivityV25.RequestMultipartInfoXml = RESTActivityV25_RequestMultipartInfoXml_Document;
            _flow.RESTActivityV25.Multipart=false;
            VTDPropertyInfoBase pi23 = new VTDPropertyInfoBase("XMLResponse","/*[local-name(.)='ArrayOfFlight'][1]/*[local-name(.)='Flight'][1]/*[local-name(.)='FlightNumber'][1]");
            VTDBaseGetter binding_getter12 = new VTDXPathGetter(pi23,XmlTypeCode.UnsignedShort);
            VTDPropertyInfoBase pi24 = new VTDPropertyInfoBase("XMLBody","/*[local-name(.)='FlightOrderDetails'][1]/*[local-name(.)='FlightNumber'][1]");
            VTDBaseSetter binding_setter12 = new VTDXPathSetter(pi24,XmlTypeCode.UnsignedShort);
            bind_dir12 = new BindDirection(_flow.RESTActivityV24,binding_getter12,binding_setter12,BindTargetType.ToInProperty);
            _flow.RESTActivityV25.InDirections.Add(bind_dir12);
            XmlDocument RESTActivityV25_ExpectedResponseXmlBody_Document = new XmlDocument();
            RESTActivityV25_ExpectedResponseXmlBody_Document.PreserveWhitespace = true;
            RESTActivityV25_ExpectedResponseXmlBody_Document.LoadXml(
@"<?xml version=""1.0""?>
<CreatedOrderParams xmlns:i=""http://www.w3.org/2001/XMLSchema-instance"" xmlns=""HP.SOAQ.SampleApp"">
	<OrderNumber>10</OrderNumber> 
	<TotalPrice>2000</TotalPrice> 
</CreatedOrderParams>");
            _flow.RESTActivityV25.ExpectedResponseXmlBody = RESTActivityV25_ExpectedResponseXmlBody_Document;
            XmlDocument RESTActivityV25_ExpectedResponseJsonBody_Document = new XmlDocument();
            RESTActivityV25_ExpectedResponseJsonBody_Document.PreserveWhitespace = true;
            RESTActivityV25_ExpectedResponseJsonBody_Document.LoadXml(
@"<F6DA54ED-92F5-4c5c-9795-170905F25080 />");
            _flow.RESTActivityV25.ExpectedResponseJsonBody = RESTActivityV25_ExpectedResponseJsonBody_Document;
            XmlDocument RESTActivityV25_ExpectedOutputProperties_Document = new XmlDocument();
            RESTActivityV25_ExpectedOutputProperties_Document.PreserveWhitespace = true;
            RESTActivityV25_ExpectedOutputProperties_Document.LoadXml(
@"<Arguments><ResponseHttpVersion></ResponseHttpVersion><StatusCode></StatusCode><StatusDescription></StatusDescription><ResponseBody></ResponseBody><ResponseBodyAsBase64></ResponseBodyAsBase64></Arguments>");
            _flow.RESTActivityV25.ExpectedOutputProperties = RESTActivityV25_ExpectedOutputProperties_Document;
            set_RESTActivityV25_checkpoints(_flow.RESTActivityV25);
            
        }
        
        internal void InitializeEncryptionManagerValues()
        {
        
        }
        	
    	bool useReport = true;
    
    	protected override STExecutionResult ExecuteStep()
        {
            return base.ExecuteStep();
        }
    
        public void Start()
        {
    	    try
    		{
    		  Workflow_Executing();
    		  this.ExecuteStep();
    		}
    		finally
    		{
    		  WorkFlowScript_Completed();
    		}
        }
    
    	private void InitReport()
    	{
    		if (useReport)
    		{	
    			// Intialize Reporter
    			string reportDBDir = Path.Combine(this._context.ReportDirectory, @"Report");
    			CleanupReport(reportDBDir);        	
    			string reportDBPath = Path.Combine(reportDBDir, "VTDReport.mdb");        	
    			if (reporter == null)
    			{
    				reporter = new Reporter(reportDBPath);
    			}
    			_context.Reporter = reporter;
    		}
    	}
    
        public static void CopyDirectory(string Src, string Dst)
        {
            String[] Files;
    
            if (Dst[Dst.Length - 1] != Path.DirectorySeparatorChar)
                Dst += Path.DirectorySeparatorChar;
            if (!Directory.Exists(Dst)) Directory.CreateDirectory(Dst);
            Files = Directory.GetFileSystemEntries(Src);
            foreach (string Element in Files)
            {
                // Sub directories
                if (Directory.Exists(Element))
                    CopyDirectory(Element, Dst + Path.GetFileName(Element));
                // Files in directory
                else
                    File.Copy(Element, Dst + Path.GetFileName(Element), true);
            }
        }
        
        private void CleanupReport(string reportDBDir)
        {   
    		if (useReport)
    		{             
    			string reportTemplateDir = Path.Combine(ServiceTestRunner.GetInstallPath(),@"bin\ReportResources");                
    			try
    			{
            		CopyDirectory(reportTemplateDir, reportDBDir);
    			}
    			catch //(Exception ex)
    			{
    				//ToDo: LoggingService.Warn("Report Cleanup Error", ex);
    			}
    		}
        }
    
        void Workflow_Executing()
        {   
        	InitReportNode();
                       
        }
    
    	private void InitReportNode()
    	{
    		if (useReport)
    		{	
        		// Init report creator
    			this.reportCreator = new HP.ST.Fwk.ReportCreator.QTPEngine.QTPEngineReportCreator();
    			this.reportLevelInTree = reportCreator.Init(_context.EnvironmentProfile.GetVariableValue("TestName"), _context);
                
    			STActivityBase activity = this;
    			string workflowID = activity.GetHashCode().ToString();
    			ReportNodeCreationData newNodeData =
    			new ReportNodeCreationData(workflowID, workflowID, DateTime.Now);
    			reporter.CreateReportNode(newNodeData);
            
    			ReportInfoData newReportData = new ReportInfoData(workflowID, ReportKeywords.TypeKeywordTag, this.GetType().ToString());
    			reporter.SendReportData(newReportData);
    			newReportData = new ReportInfoData(workflowID, ReportKeywords.NameKeywordTag, this.Name);
    			//TrackData(ReportInfoData.InfoDataTag, newReportData);
    			reporter.SendReportData(newReportData);            
            }
    	}
        
        void WorkFlowScript_Completed()
        {   
    		
    
    		CreateReportFiles();
    					
        	// Write all snapshots to disk
    		this._context.SnapshotManager.WriteSnapshotsToDisk();
    
    		OnExecutionCompleted();
    		
        }
    
    	private void CreateReportFiles()
    	{
    		if (useReport)
    		{	
    			//Dispose reporter inorder to close connection to report DB
           		this._context.Reporter.Dispose();
            	
           		// Run report creator
    			reportCreator.RunOnDBAndCreateFiles();
    		}
    	}
    
        
        void Workflow_Faulting()
        {
    		
    
    		CreateReportFiles();
            // Write all snapshots to disk
    		this._context.SnapshotManager.WriteSnapshotsToDisk();
           
    		OnExecutionCompleted();
        }
    
    	protected override QcSystemVariables GetRuntimeQcVariables(ISTRunTimeContext context)
    	{
    		return new HP.ST.Ext.BasicActivities.RuntimeQcVariables(this._context);
    	}
            
    	protected override TestSystemVariables GetTestSystemVariables(ISTRunTimeContext context)
    	{
    		return new HP.ST.Ext.BasicActivities.RuntimeTestVariables(this._context);
    	}
    
    	private void UpdateTestSettings(ISTRunTimeContext ctx)
        {
    		ctx.PropertyBag["StopTestOnStepFailure"] = true;
    	}
    }
    
    public partial class VuserClass
    {
    	public static string[] CommandLineArguments;
    	public static string[] DotNetResolverPaths;
    	
        public VuserClass()
        {
    				
    		AssemblyResolver.AddSTPathsToResolutionPaths();
    		AssemblyResolver.AttachToAppdomain();
        }
    
        private void AddAssemblyResolver()
        {
    		AssemblyResolver.AddTestPathToResolutionPaths(GetTestPath());
    		AssemblyResolver.AddPathsForAssemblyResolution(DotNetResolverPaths);
        }
    	
        public int STAction()
        {	
            AddAssemblyResolver();
            STRunTimeContext ctx = new STRunTimeContext(Directory.GetParent(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location)).FullName, string.Empty);
            WorkFlowScript script = new WorkFlowScript(ctx);
            script.InitializeComponent();
            script.Start();       
            
            return 0;
        }
        
        public void NotifyLicenseException(string msg)
        {
        		
    		try
    		{
    		    STRunTimeContext ctx = new STRunTimeContext(Directory.GetParent(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location)).FullName, string.Empty);
                WorkFlowScript script = new WorkFlowScript(ctx);
                script.InitializeComponent();
                script.Context.ReplayClient.OnLicenseFailure(msg);
                
            }
            catch (Exception)
            {
    			// ToDo: log the error message
            }        
        }
    
    	 protected string GetTestPath()
            {
                if (CommandLineArguments != null)
                {
                    for (int i = 0; i < CommandLineArguments.Length; i++)
                    {
                        if (CommandLineArguments[i].Equals("-test", StringComparison.OrdinalIgnoreCase))
                        {
                            return CommandLineArguments[i + 1];
                        }
                    }
                }
                return String.Empty;
            }
        
    }
    
    }
    